##############################################################################
# MAC_IBM:		MAC OS X Apple with IBM Compiler.
##############################################################################
F90_SER = xlf90
F90_OMP =
F90_MPI =
FLAGS_OPT = -O3 -qstrict -qtune=auto -qcache=auto -qalign=4k
FLAGS_MSC = -w -qfixed
FLAGS90_MSC = -w -qfree=f90
FLAGS_SER =
FLAGS_OMP =
FLAGS_MPI =
INCS_SER = 
INCS_OMP =
INCS_MPI =
LIBS_SER =
LIBS_OMP =
LIBS_MPI =
O_DIR =
OUT = -o 
EXTO = o
MAKE = make
RM = rm -f
swch = -unix
